### ISSUE TITLE
NoMethodError: undefined method `clear'

### ISSUE THREAD

**Issue by mdamaceno** [hanami/hanami#594]
After upgrading hanami-model from 0.6.1 to 0.6.2.1 in my project, I get the error in my tests:

```
NoMethodError: undefined method `clear' for MyRepository:Class
NoMethodError: undefined method `find' for MyRepository:Class
```

Then, I downgraded to 0.6.1 and after that, my tests are ok now.

The methods for repositories were modified?

**Comment by vasspilka** [comment]
yes now you should always create an instance of Repository and call methods on that.
Example `BookRepository.new.all`
see hanami/model#920

**Comment by jodosha** [comment]
@mdamaceno I'm terribly sorry, but `hanami-model` `0.6.2.1` was a broken release, which I now yanked from Rubygems. If you run `bundle update` in your project, it should install `0.6.1`, which is a working version.
