### ISSUE TITLE
Mailers do not work in 0.9.2 w/ hanami-mailer 0.4.0

### ISSUE THREAD

**Issue by Padgett** [hanami/hanami#723]
When generating a clean mailer with `hanami generate mailer thing` the result is not usable.

The generate command runs as expected, but attempting to use the mailer results in a `NoMethodError`

```
$ hanami generate mailer blah-blah
      create  spec/hanami_test/mailers/blah_blah_spec.rb
      create  lib/hanami_test/mailers/blah_blah.rb
      create  lib/hanami_test/mailers/templates/blah_blah.txt.erb
      create  lib/hanami_test/mailers/templates/blah_blah.html.erb
```

```
$ rake test
Run options: --seed 36746
[...]
  1) Error:
Mailers::BlahBlah#test_0001_delivers email:
NoMethodError: undefined method `fetch' for nil:NilClass
    gems/hanami-mailer-0.4.0/lib/hanami/mailer/dsl.rb:84:in `templates'
    gems/hanami-mailer-0.4.0/lib/hanami/mailer.rb:324:in `__part?'
    gems/hanami-mailer-0.4.0/lib/hanami/mailer.rb:312:in `__part'
    gems/hanami-mailer-0.4.0/lib/hanami/mailer.rb:289:in `block in build'
    gems/hanami-mailer-0.4.0/lib/hanami/mailer.rb:281:in `tap'
    gems/hanami-mailer-0.4.0/lib/hanami/mailer.rb:281:in `build'
    gems/hanami-mailer-0.4.0/lib/hanami/mailer.rb:201:in `initialize'
    gems/hanami-mailer-0.4.0/lib/hanami/mailer.rb:186:in `new'
    gems/hanami-mailer-0.4.0/lib/hanami/mailer.rb:186:in `deliver'
    hanami_test/spec/hanami_test/mailers/blah_blah_spec.rb:5:in `block (2 levels) in <top (required)>'
```

**Comment by jodosha** [comment]
I can confirm the problem, writing a fix for it.

**Comment by TrumpClone** [comment]
Check this comment. It can reveal some implementation problems https://github.com/hanami/hanami/issues/703#issuecomment-269743810

**Comment by jodosha** [comment]
Thank you.

**Comment by mereghost** [comment]
@Padgett Unfortunately it's a know issue in 0.9.2. We fixed it on hanami master already but has not been backported as we intend to release 1.0 soon.

**Comment by mereghost** [comment]
It was fixed on #705, albeit not released yet.

**Comment by dungpt3003** [comment]
Hi, I'm new to `hanami`. I encountered the same error today. How can I avoid this error when using `hanami-mailer` before having it fixed in the next version?

**Comment by mereghost** [comment]
@dungpt3003 A workaround for the mean time is to edit you `config/environment.rb` file and add that just below the mailer block:
```ruby
Hanami::Mailer.configure(&mailer)
Hanami::Mailer.load!
```

**Comment by dungpt3003** [comment]
This worked for me. Thank you for your swift response!
