### ISSUE TITLE
Config environment doesn't work with hanami 1.0.0.beta1

### ISSUE THREAD

**Issue by davydovanton** [hanami/hanami#730]
Hey, I tried to update my hanami app to 1.0, and I had error with environment:
```
/Users/anton/work/repositories/ossboard/config/environment.rb:46:in `block in <top (required)>': undefined method `environment' for #<Hanami::Configuration:0x007fe17d7a7810> (NoMethodError)
        from /Users/anton/.rvm/gems/ruby-2.3.0/gems/hanami-1.0.0.beta1/lib/hanami/configuration.rb:20:in `instance_eval'
        from /Users/anton/.rvm/gems/ruby-2.3.0/gems/hanami-1.0.0.beta1/lib/hanami/configuration.rb:20:in `initialize'
 ```

After that, I found that hanami from RubyGems doesn't have environment logic. You can see it on this record:
https://asciinema.org/a/103243

/cc @jodosha @hanami/core

**Comment by davydovanton** [comment]
UPD: sorry, I added link to private record. Fixed it now 👍

**Comment by cllns** [comment]
Did you update `config/environment.rb` as follows http://hanamirb.org/guides/upgrade-notes/v100beta1/#-code-config-environment-rb-code- ?

**Comment by davydovanton** [comment]
@cllns yep, you can see in my screencast that in my local version hanami doesn't have this functionality. But it's only my problem. Other developers don't have it

**Comment by cllns** [comment]
Hm, maybe you have the gem from GitHub instead of Rubygems?  The [version was updated to 1.0.0.beta1 on Dec 20th, 2016](https://github.com/hanami/hanami/blob/master/lib/hanami/version.rb#L9)

Try:
```
gem uninstall hanami -v 1.0.0.beta1
gem install hanami --pre
```
:)

**Comment by davydovanton** [comment]
Hey, thanks for the tip. I fixed this issue. Problem was in my local rvm 😞
